blueprint:
  name: View Assist - Search Music with Music Assistant
  description: Use various methods to search for individual songs, albums, artists,
    and playlists from your Music Assistant server (View Assist Search Music with Music
    Assistant v 1.0.0)
  domain: automation
  input:
    ma_instance:
      name: Music Assistant Instance
      description: Select the Music Assistant instance
      selector:
        config_entry:
          integration: music_assistant
    view_path:
      name: Dashboard Info view
      description: The View Assist dashboard view to use for displaying music search
        results (example /view-assist/music-search-results)
      default: /view-assist/music-search-results


    music_view_path:
      name: Music view
      description: The View Assist dashboard view to use for the music player (example
        /view-assist/music)
      default: /view-assist/music

    num_search_results:
      name: Number of search results
      description: Number of search results to display
      default: 4
      selector:
        number:
          min: 1
          max: 24


    language:
      name: Language
      description: The desired spoken language
      default: en
      selector:
        language:
          languages:
          - en
          native_name: false
          no_sort: false
    search_songs_by_artist_command:
      name: Search Songs by Artist
      description: The command to trigger action to search for songs by an artist
      default: show [me] songs by {artist}
    search_songs_by_song_command:
      name: Search Songs by Name
      description: The command to trigger action to search for songs by name
      default: show [me] songs (named|called) {song}
    search_albums_by_artist_command:
      name: Search Albums by Artist
      description: The command to trigger action to search for albums by an artist
      default: show [me] albums by {artist}
    search_albums_by_album_command:
      name: Search Albums by Name
      description: The command to trigger action to search for albums by name
      default: show [me] albums (named|called) {album}
    search_artists_by_artist_command:
      name: Search Artists by Name
      description: The command to trigger action to search for artists by name
      default: show [me] artists (named|called) {artist}

alias: View Assist - Search Music with Music Assistant
description: Search music using Music Assistant
trigger:
- trigger: conversation
  command: !input search_songs_by_artist_command
  id: searchsongsbyartist
- trigger: conversation
  command: !input search_songs_by_song_command
  id: searchsongsbysong
- trigger: conversation
  command: !input search_albums_by_artist_command
  id: searchalbumsbyartist
- trigger: conversation
  command: !input search_albums_by_album_command
  id: searchalbumsbyalbum
- trigger: conversation
  command: !input search_artists_by_artist_command
  id: searchartistsbyartist

conditions: []
actions:
- variables:
    target_satellite_device: >
      {% if trigger is defined and trigger.device_id is defined %}
        {{ view_assist_entity(trigger.device_id) }}
      {% else %}
        {{ device_id }}
      {% endif %}
    target_mediaplayer_device: '{{ state_attr(target_satellite_device, ''mediaplayer_device'')}}'
    target_satellite_device_type: '{{ state_attr(target_satellite_device, ''type'')}}'
    target_musicplayer_device: '{{ state_attr(target_satellite_device, ''musicplayer_device'')
      }}'
    target_use_announce: '{{ state_attr(target_satellite_device, ''use_announce'') }}'
    view_path: !input view_path
    music_view_path: !input music_view_path
    ma_instance: !input ma_instance
    num_search_results: !input num_search_results
    language: !input language

    play_uri: "{{ play_uri | default('UNDEFINED') }}"
    trigger_id: "{{ trigger_id | default('UNDEFINED') }}"

    translations:
      en:
        responses:
          searchsongsbyartist_found: Here are songs matching artist {artist}
          searchsongsbyartist_not_found: I was unable to find any matches for {artist}
          searchsongsbysong_found: Here are songs matching {song}
          searchsongsbysong_not_found: I was unable to find any matches for {song}
          searchalbumsbyartist_found: Here are albums matching artist {artist}
          searchalbumsbyartist_not_found: I was unable to find any matches for {artist}
          searchalbumsbyalbum_found: Here are albums matching {album}
          searchalbumsbyalbum_not_found: I was unable to find any matches for {album}
          searchartistsbyartist_found: Here are artists matching {artist}
          searchartistsbyartist_not_found: I was unable to find any matches for {artist}

    responses_localized: '{{ translations[language][''responses''] }}'

- if:
  - alias: "If the automation is being called by tapping the view"
    condition: template
    value_template: "{{ trigger_id and trigger_id == 'tapped' }}"
  then:

    - action: view_assist.set_state
      target:
        entity_id: '{{ target_satellite_device }}'
      data:
        mode: music
        title: ''
        message_font_size: 5vw

    - action: music_assistant.play_media
      continue_on_error: true
      target:
        entity_id: '{{ target_musicplayer_device }}'
      data:
        enqueue: replace
        media_id: '{{ play_uri }}'

    - delay: "00:00:01.0"

    - action: view_assist.navigate
      data:
        device: '{{ target_satellite_device }}'
        path: '{{ music_view_path }}'
  else:

    - action: system_log.write
      data:
        message: "automations entity_id: {{ this.entity_id }}"
        level: debug


    - choose:
      - conditions:
        - condition: trigger
          id:
          - searchsongsbyartist
        sequence:
        - variables:
            search_command_variable: '{artist}'
            search_media_type: track
            search_media_query: '{{ trigger.slots.artist  | trim }}'
            search_media_name: '{{ search_media_query }}'
            search_media_artist: '{{ search_media_query }}'
            search_results_type: tracks
            response_variable_found: searchsongsbyartist_found
            response_variable_not_found: searchsongsbyartist_not_found
      - conditions:
        - condition: trigger
          id:
          - searchsongsbysong
        sequence:
        - variables:
            search_command_variable: '{song}'
            search_media_type: track
            search_media_query: '{{ trigger.slots.song  | trim }}'
            search_media_name: '{{ search_media_query }}'
            search_media_artist: '{{ " " | trim }}'
            search_results_type: tracks
            response_variable_found: searchsongsbysong_found
            response_variable_not_found: searchsongsbysong_not_found
      - conditions:
        - condition: trigger
          id:
          - searchalbumsbyartist
        sequence:
        - variables:
            search_command_variable: '{artist}'
            search_media_type: album
            search_media_query: '{{ trigger.slots.artist  | trim }}'
            search_media_name: '{{ search_media_query }}'
            search_media_artist: '{{ search_media_query }}'
            search_results_type: albums
            response_variable_found: searchalbumsbyartist_found
            response_variable_not_found: searchalbumsbyartist_not_found
      - conditions:
        - condition: trigger
          id:
          - searchalbumsbyalbum
        sequence:
        - variables:
            search_command_variable: '{album}'
            search_media_type: album
            search_media_query: '{{ trigger.slots.album  | trim }}'
            search_media_name: '{{ search_media_query }}'
            search_media_artist: '{{ " " | trim }}'
            search_results_type: albums
            response_variable_found: searchalbumsbyalbum_found
            response_variable_not_found: searchalbumsbyalbum_not_found
      - conditions:
        - condition: trigger
          id:
          - searchartistsbyartist
        sequence:
        - variables:
            search_command_variable: '{artist}'
            search_media_type: artist
            search_media_query: '{{ trigger.slots.artist  | trim }}'
            search_media_name: '{{ search_media_query }}'
            search_media_artist: '{{ search_media_query }}'
            search_results_type: artists
            response_variable_found: searchartistsbyartist_found
            response_variable_not_found: searchartistsbyartist_not_found


    - action: music_assistant.search
      data:
        limit: "{{ num_search_results }}"
        config_entry_id: '{{ ma_instance }}'
        media_type:
        - '{{ search_media_type }}'
        name: '{{ search_media_name }}'
        artist: '{{ search_media_artist }}'
      response_variable: found_results
    - alias: Did we find songs by artist?
      if:
      - condition: template
        value_template: '{{found_results[search_results_type] | count>0}}'
        alias: We found an artist!
      then:
      - action: view_assist.set_state
        target:
          entity_id: '{{ target_satellite_device }}'
        data:
          mode: music-search
          title: ''
          message_font_size: 5vw
          music_search_results:
            type: "{{ search_results_type }}"
            query: "{{ search_media_query }}"
            results: "{{ found_results | tojson }}"
          target_automation: "{{ this.entity_id }}"
      - action: view_assist.navigate
        data:
          device: '{{ target_satellite_device }}'
          path: '{{ view_path }}'
      - if:
        - condition: template
          value_template: '{{ target_use_announce is not false }}'
        then:
        - variables:
            conversation_response: '{{ responses_localized[response_variable_found].replace(search_command_variable,
              search_media_query)}}'
        - set_conversation_response: '{{ conversation_response }}'
        - action: view_assist.set_state
          target:
            entity_id: '{{ target_satellite_device }}'
          data:
            last_said: '{{ conversation_response }}'
        else:
        - set_conversation_response: ''
      else:
      - if:
        - condition: template
          value_template: '{{ target_use_announce is not false }}'
        then:
        - variables:
            conversation_response: '{{ responses_localized[response_variable_not_found].replace(search_command_variable,
              search_media_query)}}'
        - set_conversation_response: '{{ conversation_response }}'
        - action: view_assist.set_state
          target:
            entity_id: '{{ target_satellite_device }}'
          data:
            last_said: '{{ conversation_response }}'
        else:
        - set_conversation_response: ''

